# Generated by Django 4.1.10 on 2023-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
